import { useEffect } from 'react';
import { useAppStore } from '../stores/useAppStore';
import { uid, getDateParts, getMonthKey } from '../utils/formatters';

// Re-export for convenience
export { suppressAutoGen } from '../utils/suppressAutoGen';

export function useRecurringAutoGen() {
  const transactions = useAppStore(s => s.transactions);
  const recurringExpenses = useAppStore(s => s.recurringExpenses);
  const month = useAppStore(s => s.month);
  const year = useAppStore(s => s.year);
  const setTransactions = useAppStore(s => s.setTransactions);
  const hydrated = useAppStore(s => s.hydrated);

  useEffect(() => {
    if (!hydrated || recurringExpenses.length === 0) return;

    const currentMonthKey = getMonthKey(month, year);
    const deletedSet = new Set(JSON.parse(localStorage.getItem('bb_autoGenDeleted') || '[]'));

    const monthTx = transactions.filter(t => {
      const parts = getDateParts(t.date);
      return parts && parts.month === month && parts.year === year;
    });

    const newTxs = [];

    recurringExpenses.filter(r => r.active).forEach(r => {
      const suppressKey = `${r.id}_${currentMonthKey}`;
      if (deletedSet.has(suppressKey)) return;

      const exists = monthTx.some(t =>
        t.desc.toLowerCase() === r.name.toLowerCase() &&
        t.category === r.category
      );

      if (!exists) {
        const dueDay = Math.min(r.dueDay, new Date(year, month + 1, 0).getDate());
        const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(dueDay).padStart(2, '0')}`;

        newTxs.push({
          id: uid(),
          date: dateStr,
          desc: r.name,
          amount: -Math.abs(r.amount),
          category: r.category,
          paid: r.autoPay || false,
          autoGenerated: true,
          recurringId: r.id,
        });
      }
    });

    if (newTxs.length > 0) {
      setTransactions([...transactions, ...newTxs]);
    }
  }, [hydrated, month, year, recurringExpenses.length]);
}
